 
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Module {
    schemaVersion?: string;
    name: string;
    description: string;
    container: OCIRuntimeConfig;
    inputChannels?: InputChannel[];
    outputChannels?: OutputChannel[];
    configSchema?: {
        [k: string]: unknown;
    } | null;
    configUISchema?: {
        [k: string]: unknown;
    } | null;
    iconUrl?: string | null;
}
export interface OCIRuntimeConfig {
    image: string;
    tag?: string;
    cwd?: string | null;
    env?: EnvVar[];
    args?: Argument[];
}
export interface EnvVar {
    name: string;
    value?: string | null;
    property?: string | null;
}
export interface Argument {
    name: string;
    value?: string | null;
    property?: string | null;
}
export interface InputChannel {
    id: string;
    required?: boolean;
    supportedFilePatterns?: string[] | null;
}
export interface OutputChannel {
    id: string;
    generatedFilePattern?: string | null;
}
