 
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type IOCardinality = "single" | "multiple";

export interface Module {
    schemaVersion?: string;
    name: string;
    description: string;
    container: OCIRuntimeConfig;
    inputChannels?: InputChannel[];
    outputChannels?: OutputChannel[];
    envSchema?: unknown;
    envUISchema?: unknown;
    argsSchema?: unknown;
    argsUISchema?: unknown;
    iconUrl?: string | null;
}
export interface OCIRuntimeConfig {
    image: string;
    tag?: string;
    cwd?: string | null;
    env?: EnvVarValueMapping[];
    args?: string[];
}
export interface EnvVarValueMapping {
    envVar: string;
    value: unknown;
}
export interface InputChannel {
    id: string;
    name: string;
    description: string;
    cardinality?: IOCardinality & string;
    required?: boolean;
    supportedFilePatterns?: string[] | null;
}
export interface OutputChannel {
    id: string;
    name: string;
    description: string;
    cardinality?: IOCardinality & string;
    generatedFilePattern?: string | null;
}
