 
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Plugin {
    schemaVersion?: string;
    plugin: ImportPlugin | ExportPlugin;
}
export interface ImportPlugin {
    name: string;
    type: "import";
    importMenuItem: string;
    importFunction: unknown;
}
export interface ExportPlugin {
    name: string;
    type: "export";
    exportMenuItem: string;
    exportFunction: unknown;
}
