/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Plugin {
    schemaVersion?: string;
    plugin: WorkflowImportPluginInstance | WorkflowExportPluginInstance;
}
export interface WorkflowImportPluginInstance {
    name: string;
    type: "workflowImport";
    importMenuItem: string;
    importFunction: unknown;
}
export interface WorkflowExportPluginInstance {
    name: string;
    type: "workflowExport";
    exportMenuItem: string;
    exportFunction: unknown;
}
