 
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Workflow {
    schemaVersion?: string;
    name: string;
    tasks?: {
        [k: string]: Task;
    };
    environments?: {
        [k: string]: Environment;
    };
}
export interface Task {
    moduleRepo?: string | null;
    moduleRev?: string | null;
    modulePath: string;
    moduleConfig: ModuleConfig;
    environment?: string | null;
}
export interface ModuleConfig {
    inputs?: {
        [k: string]: string;
    };
    outputs?: {
        [k: string]: string;
    };
    env?: {
        [k: string]: unknown;
    };
    args?: string[];
}
export interface Environment {
    name: string;
    baseDir: string;
    dataMappings?: {
        [k: string]: string;
    };
}
