 
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Workflow {
    schemaVersion?: string;
    name: string;
    tasks?: Task[];
    environments?: Environment[];
}
export interface Task {
    id: string;
    module: string;
    moduleConfig: ModuleConfig;
    moduleRepo?: string | null;
    moduleRev?: string | null;
    environment?: string | null;
}
export interface ModuleConfig {
    inputs?: ChannelResourceMapping[];
    outputs?: ChannelResourceMapping[];
    env?: EnvVarValueMapping[];
    args?: string[];
}
export interface ChannelResourceMapping {
    channel: string;
    resource: string;
}
export interface EnvVarValueMapping {
    envVar: string;
    value: unknown;
}
export interface Environment {
    id: string;
    baseDir: string;
}
