 
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Workflow {
    schemaVersion?: string;
    name: string;
    tasks?: Task[];
}
export interface Task {
    id: string;
    repo?: string | null;
    rev?: string | null;
    module: string;
    inputs?: ChannelResourceMapping[];
    outputs?: ChannelResourceMapping[];
    config?: {
        [k: string]: unknown;
    };
    props?: TaskNodeProperties | null;
}
export interface ChannelResourceMapping {
    channel: string;
    resource: string;
}
export interface TaskNodeProperties {
    posx: number;
    posy: number;
    width?: number | null;
    height?: number | null;
}
