name: deploy
on:
    push:
        branches:
            - main
    workflow_dispatch:
jobs:
    pages:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            pages: write
            id-token: write
        concurrency:
            group: "pages"
            cancel-in-progress: true
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - uses: actions/configure-pages@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: "18"
                  cache: "npm"
            - name: Install dependencies
              run: npm install
            - name: Build
              run: npm run build
              env:
                  BASE_URL: "/viuws-editor/"
            - uses: actions/upload-pages-artifact@v2
              with:
                  path: "./dist"
            - uses: actions/deploy-pages@v2
              id: deployment
