name: Deploy
on:
    push:
        branches:
            - main
    workflow_dispatch:
jobs:
    pages:
        name: GitHub Pages
        runs-on: ubuntu-latest
        permissions:
            contents: read
            pages: write
            id-token: write
        concurrency:
            group: "pages"
            cancel-in-progress: true
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        steps:
            - uses: actions/checkout@v3
              name: Checkout repository
              with:
                  fetch-depth: 0
            - uses: actions/setup-node@v3
              name: Set up Node.js
              with:
                  node-version: "18"
                  cache: "npm"
            - name: Install dependencies
              run: npm install
            - name: Build website
              run: npm run build
              env:
                  BASE_URL: "/viuws/"
            - uses: actions/configure-pages@v3
              name: Configure GitHub Pages
            - uses: actions/upload-pages-artifact@v2
              name: Upload artifact
              with:
                  path: "./dist"
            - uses: actions/deploy-pages@v2
              name: Deploy to GitHub Pages
              id: deployment
